version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql_workout_app
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "7432:5432"
    restart: always
    networks:
      - default